# .pre-commit-config.yaml
repos:
  - repo: https://github.com/psf/black
    rev: 23.12.1 # Matches ^23.0 from pyproject.toml
    hooks:
      - id: black
        args: [ zephflow/, tests/ ]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0 # Matches ^5.0 from pyproject.toml
    hooks:
      - id: isort
        args: [ zephflow/, tests/ ]

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0 # Matches ^6.0 from pyproject.toml
    hooks:
      - id: flake8
        args: [ zephflow/ ]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0 # Matches ^1.0 from pyproject.toml
    hooks:
      - id: mypy
        args: [ --config-file=pyproject.toml, zephflow/ ]
        pass_filenames: false
        additional_dependencies:
          - "requests>=2.32.0,<3.0.0"
          - "types-requests<2.32"